version: 2.0
jobs:
  jupyterexecute:
    docker:
      - image: gudhi/tda_tutorial_for_ci:latest
    steps:
      - checkout
      - run:
          name: Convert and executes all notebooks
          command: |
            for f in *.ipynb; do echo "Processing $f file.."; jupyter nbconvert --to notebook --inplace --execute $f;done;
            
workflows:
  version: 2
  build:
    jobs:
      - jupyterexecute